version: '2'

services:
  web:
    build: .
    image: honestbee/base_img
    container_name: honestbee_web_app
    privileged: true
    tty: true
    expose:
     - "80"
    ports:
     - "8000:80"
    volumes:
     - /opt/honestbee:/opt/honestbee
